# Generated by Django 4.1.4 on 2022-12-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('inf', models.TextField(max_length=200, verbose_name='Информация')),
                ('price', models.FloatField(default=1, verbose_name='Цена$')),
                ('pub_date', models.DateField()),
            ],
            options={
                'ordering': ('-price',),
            },
        ),
    ]
