# Generated by Django 4.1.4 on 2022-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_computers_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='computers',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
