# Generated by Django 4.1.4 on 2022-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_computers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
