# Generated by Django 4.1.4 on 2022-12-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_computers_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
