# Generated by Django 4.1.4 on 2022-12-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_computers_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='pub_date',
        ),
    ]
