# Generated by Django 4.1.4 on 2022-12-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_computers_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
